# Generated by Django 5.0.6 on 2024-07-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_market_operationchain_futuresoptionsoperation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
