# Generated by Django 5.0.6 on 2024-07-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_market_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresoperation',
            name='contract',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='futuresoptionsoperation',
            name='strike_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockoperation',
            name='shares_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
