# Generated by Django 5.0.6 on 2024-07-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_futuresoperation_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresoperation',
            name='type',
            field=models.CharField(choices=[('stock', 'Stock'), ('futures', 'Futures'), ('options', 'Options')], default=1, editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='futuresoptionsoperation',
            name='type',
            field=models.CharField(choices=[('stock', 'Stock'), ('futures', 'Futures'), ('options', 'Options')], default=1, editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockoperation',
            name='type',
            field=models.CharField(choices=[('stock', 'Stock'), ('futures', 'Futures'), ('options', 'Options')], default=1, editable=False, max_length=50),
            preserve_default=False,
        ),
    ]
