# Generated by Django 5.0.6 on 2024-07-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_alter_futuresoperation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationchain',
            name='chain_number',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
