# Generated by Django 5.0.6 on 2024-07-28 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_operationchain_chain_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationchain',
            name='chain_number',
        ),
    ]
