# Generated by Django 5.0.6 on 2024-07-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_remove_operationchain_chain_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationchain',
            name='chain_number',
            field=models.CharField(default=2024000001, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
