# Generated by Django 5.0.6 on 2024-08-01 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0018_commissions_operationcommission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissions',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commissions',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_commissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
