# Generated by Django 5.0.6 on 2024-08-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0020_alter_stockoperation_shares_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuresoperation',
            name='transaction_type',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='futuresoptionsoperation',
            name='transaction_type',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='stockoperation',
            name='transaction_type',
            field=models.CharField(max_length=4),
        ),
    ]
