# Generated by Django 5.0.6 on 2024-08-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0022_operationcommission_currency_alter_market_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingcompany',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tradingcompany',
            name='modified_by',
        ),
    ]
