# Generated by Django 5.0.6 on 2024-08-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0023_remove_tradingcompany_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingaccount',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='modified_by',
        ),
    ]
